### ISSUE TITLE
Too easy to accidentally reposition events on mobile web UI

### ISSUE THREAD

**Issue by wearsshoes** [kazad/pastecal#1]
User report on an event that I am coordinating via pastecal says, "Opened this on mobile and trying to scroll resulted in the drum circle event getting rearranged. This happened immediately so I have no idea where it was in the schedule before, could someone who knows fix?"

When investigating further, I made some other difficult-to-reverse changes as well.  Perhaps some possible solutions might be different number of fingers required for scrolling and moving events, or edit versus viewing modes, or a confirm dialogue before submitting changes on mobile, or else an undo button?

**Comment by savraj** [comment]
yes we need this fixed

**Comment by kazad** [comment]
Great suggestion, fix has been deployed. I looked in the options and found a way to disable moving/resizing events when you're on a touchscreen device. (In the future, this may become more fine-grained (edit/view mode etc.) but that should fix the core usability issue.)
