### ISSUE TITLE
Allow ical feeds to sync with calendar clients

### ISSUE THREAD

**Issue by patcon** [kazad/pastecal#3]
Hi! this is a super neat tool! Thanks for making it available ❤️ 

Do you think it would be hard to create ical feeds so that people could view it within their calendar clients (desktop, google, etc)?

**Comment by kazad** [comment]
Glad you're enjoying it! The library I'm using supports a one-time iCal export, I'll need to figure out how to expose it server-side for a live feed. Appreciate the suggestion.

**Comment by edsaperia** [comment]
This would be fantastic 😍

**Comment by kazad** [comment]
I've added the feature! Just add .ics to the end of your pastecal URL.

`https://pastecal.com/yourcalendar.ics`

Just whipped it up quickly (thanks GPT!), there may be bugs, but hope it works.
