### ISSUE TITLE
Unexpected behaviour when modifying repeating calendar series event  

### ISSUE THREAD

**Issue by cavit8** [kazad/pastecal#8]
Howdy. Attempting to modify a repeating calendar on an event basis rather than a series creates a duplicate series with the change. For example, changing the description adds a new series with the change, keeping the original series as a distinct parallel series. This rather than what I expected - a change in the single calendar event in the series (say, adding an attendees's name in the description) leaving the rest of the series unchanged.

Perhaps I don't have a clear idea of what is intended with the edit function. An exceptionally useful tool - I manage a NFP and getting people to register for a common account to use a proprietary shared calendar like a google calendar is like herding cats. This is much easier :-)

**Comment by kazad** [comment]
Thanks for the report, glad you're enjoying it! Just fixed, you should now be able to edit an event in a series without creating a duplicate.
